apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful-app
  annotations:
    gremlin.com/service-id: stateful-app
spec:
  serviceName: "stateful-app"
  replicas: 1
  selector:
    matchLabels:
      app: stateful-app
  template:
    metadata:
      labels:
        app: stateful-app
      annotations:
        gremlin.com/service-id: stateful-app
    spec:
      restartPolicy: Always
      containers:
      - name: stateful-app
        image: nginx
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"

