components:
  accountingService:
    enabled: true
    replicas: 2
  adService:
    enabled: true
    replicas: 2
  cartService:
    enabled: true
    replicas: 2
  checkoutService:
    enabled: true
    replicas: 2
  currencyService:
    enabled: true
    replicas: 2
  emailService:
    enabled: true
    replicas: 2
  frontend:
    enabled: true
    replicas: 2
  frontendProxy:
    enabled: true
    replicas: 2
    service:
      type: LoadBalancer
    ingress:
      enabled: true
      ingressClassName: alb
      annotations:
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: instance
        alb.ingress.kubernetes.io/target-node-labels: kubernetes.io/os=linux
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
        #alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80},{"HTTPS": 443}]'
      hosts:
        - host: ""
          paths:
            - path: /
              pathType: Prefix
              port: 8080 
  paymentService:
    enabled: true
    replicas: 2
  productCatalogService:
    enabled: true
    replicas: 2
  quoteService:
    enabled: true
    replicas: 2
  recommendationService:
    enabled: true
    replicas: 2
  shippingService:
    enabled: true
    replicas: 2
